import {
  ArrowUpRightIcon,
  BuildingLibraryIcon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterIcon,
} from "@heroicons/react/24/solid";
import { type GetStaticProps, type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { getHome } from "~/api/Home";
import {
  Button,
  DefaultHeader,
  FAQ,
  FeedbackForm,
  ServiceCard,
  ServicePricingCard,
  Testimonials,
  TestimonialsMap,
  Typography,
} from "~/components";
import {
  type FAQ as IFAQ,
  type Homepage,
  type Testimonial,
  type Promo,
} from "~/models/api";
import { type Team } from "~/models/api/Team";
import { toast } from "react-toastify";
import { type Service } from "~/models/api/Service";

const Home: NextPage<IHomeProps> = ({
  page: { attributes: page },
  services,
  faq,
  team,
  testmonials,
  promos,
}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultHeader title={page.title} button={page.headerLink} />
      <section className="container mt-10 grid py-10 md:grid-cols-2 lg:mt-40 lg:grid-cols-3">
        {services.map((service) => (
          <ServiceCard
            title={service.attributes.title}
            image={service.attributes.image}
            key={service.id}
            slug={`/services/${service.attributes.slug}`}
            hiddenTitle
            {...service}
          />
        ))}
        <ServiceCard slug="/" title="Запись на бесплатный разбор" promo />
      </section>
      <section className="container pb-24 pt-10">
        <Typography as="h2" variant="big" className="uppercase text-white">
          Пакеты / Стоимость
        </Typography>
        <div className="pt-10">
          {promos?.map((promo, index) => (
            <ServicePricingCard
              title={promo.attributes.title}
              discount={promo.attributes.discount}
              index={index}
              key={promo.id}
              className="mb-3"
              href={"#form"}
            />
          ))}
          <div className="flex justify-end pt-10">
            <Button icon={<ArrowUpRightIcon />} className="w-full md:w-fit">
              Записаться на бесплатный разбор
            </Button>
          </div>
        </div>
      </section>
      <section className="relative pb-36 pt-24">
        <div className="container">
          <Typography as="h2" variant="big" className="uppercase text-white">
            {page.gainTitle.split(" ").map((word, index) => (
              <span key={index} className="block">
                {word}
              </span>
            ))}
          </Typography>
          <div className="flex justify-end pt-2">
            <div className="mt-10 grid grid-cols-2 gap-x-10 gap-y-4 md:mt-0 md:w-2/3 md:gap-x-0 lg:gap-y-10">
              {page.gains.map((gain, index) => (
                <Typography
                  as="h4"
                  variant="body1"
                  className="tracking-wider text-white"
                  key={gain.id}
                >
                  {index !== page.gains.length - 1 && (
                    <ArrowUpRightIcon className="mr-4 inline w-5 text-accent" />
                  )}
                  <span
                    className={
                      index === page.gains.length - 1 ? "bg-primary px-2" : ""
                    }
                  >
                    {gain.text}
                  </span>
                </Typography>
              ))}
            </div>
          </div>
          <div
            className="absolute
		right-0 top-1/2 h-64 w-64 -translate-y-1/2 translate-x-3/4
		transform rounded-full bg-gradient-to-br from-accent/30 
		to-accent shadow-2xl shadow-accent blur-3xl filter"
          />
        </div>
        <span className="absolute right-0 top-20 text-7xl font-bold uppercase tracking-wider text-secondary/25">
          Media
        </span>
        <span className="absolute left-0 top-1/3 mt-10 max-w-3xl pb-10 pl-10 pt-24 text-7xl font-bold uppercase tracking-wider text-secondary/10">
          DIGITAL-MARKETING
        </span>
      </section>

      <section className="container py-24">
        <Typography as="h2" variant="big" className="uppercase text-white">
          <span className="border-b-2 pb-1">отзывы</span>
        </Typography>
        <TestimonialsMap testimonials={testmonials} />
        <Testimonials testimonials={testmonials} className="lg:-mt-32" />
      </section>

      <section className="container grid py-10 md:grid-cols-3">
        <Typography
          as="h2"
          variant="big"
          className="col-span-1 uppercase text-white"
        >
          <span className="border-b-2 pb-1">Q&A</span>
        </Typography>
        <div className="col-span-2">
          <FAQ faqs={faq} />
        </div>
      </section>
      <div id="form" className="pt-14">
        <FeedbackForm
          onSubmit={() => {
            toast.success("Ваша заявка успешно отправлена");
          }}
        />
      </div>
      <section className="container pb-20 pt-40">
        <Typography
          as="h2"
          variant="big"
          className="col-span-1 uppercase text-white"
        >
          СЛУЖБА ЗАБОТЫ
        </Typography>
        <div className="mt-28 items-center justify-between border-b border-white pb-20 md:flex">
          <div>
            <Typography
              as="h3"
              variant="body2"
              weight="bold"
              className="text-accent"
            >
              Написать:
            </Typography>
            <Typography as="div" variant="body1" className="mt-1 text-white">
              <a href="mailto:sassen@mediamarketing.com" target="_blank">
                sassen@mediamarketing.com
              </a>
            </Typography>
          </div>
          <div className="mt-12 flex gap-10 text-white md:mt-0">
            <BuildingLibraryIcon className="w-10" />
            <CalendarDaysIcon className="w-10" />
            <ChatBubbleBottomCenterIcon className="w-10" />
          </div>
        </div>
      </section>
      <section className="bg-primary pb-14 pt-20 lg:pt-40">
        <div className="container grid gap-10 md:grid-cols-2">
          <div className="flex flex-col justify-between">
            <Typography
              as="h2"
              variant="big"
              className="col-span-1 border-b-2 border-white pb-10 uppercase text-white"
            >
              {page.aboutTitle}
            </Typography>
            <Typography as="p" variant="body-big" className="mt-10 text-white">
              {page.aboutText}
            </Typography>
          </div>
          <Image
            src="https://source.unsplash.com/random?studio&size=633x455"
            alt="studio"
            width={633}
            height={455}
          />
        </div>
      </section>
      <section className="container relative py-20 md:py-40">
        <Typography
          as="p"
          variant="body-big"
          className="mt-10 max-w-5xl text-white"
        >
          {page.outro}
        </Typography>
        <div className="relative z-10 mt-20 grid max-w-5xl grid-cols-1 gap-10 md:grid-cols-2 lg:mt-40 lg:gap-20">
          {page.outroItems?.map((item, index) => (
            <div key={index}>
              <Typography as="span" variant="h3" className="text-white">
                {index + 1}
              </Typography>
              <div className="my-4 h-0.5 w-48 bg-white" />
              <Typography
                as="p"
                variant="body2"
                className="mt-10 max-w-5xl text-white"
              >
                {page.outro}
              </Typography>
            </div>
          ))}
        </div>
        <Image
          className="absolute bottom-20 right-0 hidden xl:block"
          src="/mockup.png"
          width={548}
          height={593}
          alt={""}
        />
      </section>
      <section className="container py-20">
        <Typography
          as="h4"
          variant="h1"
          className="col-span-1 mx-auto max-w-4xl uppercase text-white"
          align="center"
        >
          {page.twoBlocksTitle}
        </Typography>
        <div className="mt-28 grid gap-6 lg:grid-cols-2">
          {page.twoBlocks.map((item, index) => (
            <div
              className="flex flex-col bg-primary px-9 py-14 text-white"
              key={item.id}
            >
              <Typography
                as="h4"
                variant="h1"
                className="col-span-1 mb-10 max-w-xl"
                weight="regular"
              >
                {item.title}
              </Typography>
              {item.items.map((item, index) => (
                <div className="flex" key={item.id}>
                  <ArrowUpRightIcon className="mr-4 w-5" />
                  <Typography as="span" variant="body1">
                    {item.text}
                  </Typography>
                </div>
              ))}
              <div className="flex-grow" />
              <Typography
                as="span"
                variant="body2"
                className="mt-10 block max-w-lg"
              >
                {item.description}
              </Typography>
            </div>
          ))}
        </div>
      </section>
      <section className="container relative pb-72 pt-40">
        <Typography
          as="h4"
          variant="h1"
          className="col-span-1 mx-auto max-w-4xl uppercase text-white"
          align="center"
        >
          Давайте работать вместе, чтобы раскрыть весь потенциал твоего бизнеса
          в мире <span className="bg-primary px-2">DIGITAL</span>
        </Typography>
        <div
          className="absolute
		left-1/2 top-1/2 h-80 w-80 -translate-x-1/2 -translate-y-1/2
		transform rounded-full bg-gradient-to-br from-accent/10 
		to-accent/30 shadow-2xl shadow-accent/40 blur-3xl filter"
        />
        <span className="absolute right-0 top-0 text-7xl font-bold uppercase tracking-wider text-secondary/25">
          media
        </span>
        <span className="absolute left-0 top-2/3 max-w-3xl pb-10 pl-10 pt-24 text-7xl font-bold uppercase tracking-wider text-secondary/25">
          DIGITAL-MARKETING
        </span>
      </section>
      <section className="container py-40">
        <Typography
          as="h2"
          variant="big"
          align="center"
          className="col-span-1 uppercase text-white"
        >
          Наша команда
        </Typography>
        <div className="grid gap-24 pt-40 text-white lg:grid-cols-3">
          {team.map((item) => (
            <div className="grid" key={item.id}>
              <div className="mb-10 flex items-end">
                <div className="relative flex-grow pb-[100%]">
                  <Image
                    src={
                      item.attributes.image?.data
                        ? "http://146.19.80.223:1337" +
                          item.attributes.image?.data?.attributes.url
                        : "https://source.unsplash.com/random?ceo&size=400x400"
                    }
                    width={400}
                    height={400}
                    className="absolute inset-0 h-full w-full object-cover"
                    alt={item.attributes.image?.data?.attributes.url}
                  />
                </div>
                <div className="h-[90%] w-5 bg-primary" />
              </div>
              <Typography as="h4" variant="h2" weight="regular">
                {item.attributes.name}
              </Typography>
              <div className="mb-8 mt-2 h-px w-48 bg-accent" />
              <Typography as="p" variant="h2" weight="regular">
                {item.attributes.role}
              </Typography>
            </div>
          ))}
          <div className="grid">
            <div className="mb-10 flex items-end">
              <div className="relative flex-grow pb-[100%]">
                <Image
                  src={
                    "http://146.19.80.223:1337/uploads/sassen_ai_ed9fb72814.png"
                  }
                  fill
                  alt={""}
                />
              </div>
              <div className="h-[90%] w-5 bg-gray-700" />
            </div>
            <Typography as="h4" variant="h2" weight="regular">
              Нейросеть
            </Typography>
            <div className="mb-8 mt-2 h-px w-48 bg-accent" />
            <Typography as="p" variant="h2" weight="regular">
              Делает всё остальное
            </Typography>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const response = await getHome();
  return {
    revalidate: 10,
    props: {
      page: response[0]?.data,
      services: response[1]?.data,
      faq: response[2]?.data,
      team: response[3]?.data,
      testmonials: response[4]?.data,
      promos: response[5]?.data,
    },
  };
};

interface IHomeProps {
  page: Homepage;
  services: Service[];
  faq: IFAQ[];
  team: Team[];
  testmonials: Testimonial[];
  promos: Promo[];
}
